/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
Authors:
 */

package mapeamento;

import javax.swing.JFrame;

/**
 *
 * @author Gus
 */
public class Abertura extends javax.swing.JFrame {

    /**
     * Creates new form Abertura
     */
    /*
    private PDI pdi;
   private Arquivo arq = new Arquivo(); 
   */
    public Abertura() {
        initComponents();
       // Tools.enable(false);
        setTitle("Principal");
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setSize(800, 600);
        this.setVisible(true);
        System.out.println();
    }

    public void alteraLabelrodape(String text){
        labelRodape.setText(text);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        labelRodape = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        File = new javax.swing.JMenu();
        Carregabd = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        itemMap = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        Exit = new javax.swing.JMenuItem();
        Tools = new javax.swing.JMenu();
        processarImagens = new javax.swing.JMenuItem();
        simularRequeima = new javax.swing.JMenuItem();
        help = new javax.swing.JMenu();
        Sobre = new javax.swing.JMenuItem();

        jLabel1.setText("jLabel1");

        jPanel1.setBackground(new java.awt.Color(0, 153, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 255, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelRodape.setText("Principal");

        jMenuBar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        File.setText("Arquivo");

        Carregabd.setText("Carrega BD");
        Carregabd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarregabdActionPerformed(evt);
            }
        });
        File.add(Carregabd);
        File.add(jSeparator1);

        itemMap.setText("Mapa");
        itemMap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMapActionPerformed(evt);
            }
        });
        File.add(itemMap);
        File.add(jSeparator2);

        Exit.setText("Exit");
        File.add(Exit);

        jMenuBar1.add(File);

        Tools.setText("Ferramentas");
        Tools.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToolsActionPerformed(evt);
            }
        });

        processarImagens.setText("Processar imagens em lote ");
        processarImagens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processarImagensActionPerformed(evt);
            }
        });
        Tools.add(processarImagens);

        simularRequeima.setText("Simular infestação de requeima");
        Tools.add(simularRequeima);

        jMenuBar1.add(Tools);

        help.setText("Ajuda");
        help.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpActionPerformed(evt);
            }
        });

        Sobre.setText("Sobre");
        Sobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SobreActionPerformed(evt);
            }
        });
        help.add(Sobre);

        jMenuBar1.add(help);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(179, Short.MAX_VALUE)
                .addComponent(labelRodape, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(279, Short.MAX_VALUE)
                .addComponent(labelRodape))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void helpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_helpActionPerformed

    private void SobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SobreActionPerformed
Help janela = new Help();
        this.setContentPane(janela);
        this.getContentPane().repaint();
        this.validate();
        // TODO add your handling code here:
    }//GEN-LAST:event_SobreActionPerformed

    private void itemMapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMapActionPerformed
        // TODO add your handling code here
  
        Mapa janela = new Mapa();
        this.setContentPane(janela);
        this.getContentPane().repaint();
        this.validate();
        Tools.enable(true);
    }//GEN-LAST:event_itemMapActionPerformed

    private void CarregabdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarregabdActionPerformed
        // TODO add your handling code here:
        CarregaBD janela = new CarregaBD();
        this.setContentPane(janela);
        this.getContentPane().repaint();
        this.validate();
        Tools.enable(true);
    }//GEN-LAST:event_CarregabdActionPerformed

    private void ToolsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToolsActionPerformed

    }//GEN-LAST:event_ToolsActionPerformed

    private void processarImagensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processarImagensActionPerformed
        // TODO add your handling code here:
        //fazer mensagens da situação do processamento futuramente->contrução
        
        Processamento janela = new Processamento();
        this.setContentPane(janela);
        this.getContentPane().repaint();
        this.validate();
        
       /* Forma antiga
        pdi= new PDI(arq);
        
        if(pdi.verificaNecessidade()){
        arq.escolheDir();
       // habilitaMenusPasta();
        //labelPath.setText(" "+arq.getPath());
        //seta as imagens que estão no diretório
        pdi.setImagens(arq.abreArquivos(arq.getPath()));
        //diminuir as imagens
        pdi.reduzDefinicaoLote(pdi.getImagens());
        //processar e guardar no banco.
        pdi.processarEArmazernar(pdi.getImagens(),11,0.6,0.05,2.0,0.0,0.0);}
        else{
            System.out.println("Não há imagens a ser processada!");
        }*/
    }//GEN-LAST:event_processarImagensActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Abertura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Abertura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Abertura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Abertura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Abertura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Carregabd;
    private javax.swing.JMenuItem Exit;
    private javax.swing.JMenu File;
    private javax.swing.JMenuItem Sobre;
    private javax.swing.JMenu Tools;
    private javax.swing.JMenu help;
    private javax.swing.JMenuItem itemMap;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JLabel labelRodape;
    private javax.swing.JMenuItem processarImagens;
    private javax.swing.JMenuItem simularRequeima;
    // End of variables declaration//GEN-END:variables
}
