/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mapeamento;


import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author Gus
 */
public class TomateDialog extends javax.swing.JDialog {

    Tomates tom;

    /**
     * Creates new form TesteDialog
     */
    public TomateDialog(java.awt.Frame parent, boolean modal, Tomates tom) {
        super(parent, modal);
        initComponents();
       // System.out.println(tom.getLinha());
        
        labelNomearquivo.setText(labelNomearquivo.getText() +" "+tom.getNomeArquivo());
        labelVermelhos.setText(labelVermelhos.getText() +" "+ tom.getVermelhos());
        labelVerdes.setText(labelVerdes.getText() +" "+ tom.getVerdes());
        labelNumtom.setText(labelNumtom.getText() +" "+ tom.getNumTom());
        labelRua.setText(labelRua.getText() +" "+ tom.getRua());
        labelLinha.setText(labelLinha.getText() +" "+ tom.getLinha());
        //labelLong.setText(labelLong.getText() +" "+ tom.getLongi());
        //labelLat.setText(labelLat.getText() +" "+ tom.getLat());
        labelData.setText(labelData.getText() +" "+ tom.getData());
        //imagem do estado
        labelEstado.setText(labelEstado.getText() +" "+ tom.getEstado());
        ImageIcon img1 = new ImageIcon(getClass().getResource("/mapeamento/ESTADOS/estado"+tom.getEstado()+".jpg"));
         ImageIcon thumbnail1 = null;
        thumbnail1 = new ImageIcon(  
         img1.getImage().getScaledInstance(130, 140, Image.SCALE_DEFAULT)); 
        labelEstado.setIcon(img1);
        
        //imagem do tomateiro
        ImageIcon img = new ImageIcon(getClass().getResource("/mapeamento/fotos_tomates/"+tom.getNomeArquivo()));
         ImageIcon thumbnail = null;
        thumbnail = new ImageIcon(  
         img.getImage().getScaledInstance(220, 240, Image.SCALE_DEFAULT)); 
        labelImagem.setIcon(thumbnail);             
        
    }

    private TomateDialog(JFrame jFrame, boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public Tomates getTom() {
        return tom;
    }

    public void setTom(Tomates tom) {
        this.tom = tom;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelNomearquivo = new javax.swing.JLabel();
        labelVermelhos = new javax.swing.JLabel();
        labelVerdes = new javax.swing.JLabel();
        labelNumtom = new javax.swing.JLabel();
        labelRua = new javax.swing.JLabel();
        labelLinha = new javax.swing.JLabel();
        labelLong = new javax.swing.JLabel();
        labelLat = new javax.swing.JLabel();
        labelImagem = new javax.swing.JLabel();
        labelData = new javax.swing.JLabel();
        labelEstado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labelNomearquivo.setText("NomeArquivo:");

        labelVermelhos.setText("Pxs Vermelhos:");

        labelVerdes.setText("Pxs Verdes:");

        labelNumtom.setText("NumTom:");

        labelRua.setText("Rua:");

        labelLinha.setText("Linha:");

        labelLong.setText("Longitude:");

        labelLat.setText("Latitude: ");

        labelImagem.setText("Imagem");

        labelData.setText("Data:");

        labelEstado.setText("Estado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(labelImagem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelEstado)
                        .addGap(78, 78, 78))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelVermelhos)
                                    .addComponent(labelVerdes)
                                    .addComponent(labelNumtom)
                                    .addComponent(labelRua)
                                    .addComponent(labelLinha))
                                .addGap(149, 149, 149))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(labelNomearquivo)
                                .addGap(154, 154, 154)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelLong)
                            .addComponent(labelData)
                            .addComponent(labelLat))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNomearquivo)
                    .addComponent(labelLong))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelVermelhos)
                    .addComponent(labelLat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelVerdes)
                    .addComponent(labelData))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelNumtom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelRua)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelLinha)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEstado)
                    .addComponent(labelImagem))
                .addContainerGap(132, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TomateDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TomateDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TomateDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TomateDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TomateDialog dialog = new TomateDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelData;
    private javax.swing.JLabel labelEstado;
    private javax.swing.JLabel labelImagem;
    private javax.swing.JLabel labelLat;
    private javax.swing.JLabel labelLinha;
    private javax.swing.JLabel labelLong;
    private javax.swing.JLabel labelNomearquivo;
    private javax.swing.JLabel labelNumtom;
    private javax.swing.JLabel labelRua;
    private javax.swing.JLabel labelVerdes;
    private javax.swing.JLabel labelVermelhos;
    // End of variables declaration//GEN-END:variables
}
